apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: nginx-blue
   namespace: blue-green
   labels:
      k8s: nginx-blue
spec:
   strategy:
      rollingUpdate:
         maxSurge: 2
         maxUnavailable: 0
      type: RollingUpdate
   replicas: 5
   template:
      metadata:
         labels:
            app: nginx
            version: blue
      spec:
         containers:
         - image: luanngominh/nginx:blue
           name: nginx-container
           ports:
           - containerPort: 80
           imagePullPolicy: Always
